services:
  postgres:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: root
      PGUSER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres2:/data/postgres2
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  server:
    image: murilo1704/ordens-de-servico-server
    container_name: server
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSL: ${DB_SSL}
      SECRET_JWT: ${SECRET_JWT}
    depends_on:
      - postgres
    networks:
      - ordens-de-servico

  front:
    image: murilo1704/ordens-de-servico-front
    container_name: front
    ports:
      - 80:80
    depends_on:
      - server
    networks:
      - ordens-de-servico

networks:
  ordens-de-servico:
    name: network-ordens-de-servico
    driver: bridge

volumes:
  postgres2: